version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canvas-server
    image: canvas-server:latest
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      CANVAS_SERVER_CONFIG: ${CANVAS_SERVER_CONFIG:-./config}
      CANVAS_SERVER_HOME: ${CANVAS_SERVER_HOME:-./user}
      CANVAS_SERVER_DATA: ${CANVAS_SERVER_DATA:-./data}
      CANVAS_SERVER_VAR: ${CANVAS_SERVER_VAR:-./var}
    volumes:
      - ${CANVAS_SERVER_CONFIG}:/opt/canvas-server/config
      - ${CANVAS_SERVER_HOME}:/opt/canvas-server/user
      - ${CANVAS_SERVER_DATA}:/opt/canvas-server/data
      - ${CANVAS_SERVER_VAR}:/opt/canvas-server/var
